### PR TITLE
feat(Contentful): Integrate data into layout

### LINKED ISSUE #152: Typography - Headings + Markdown (Presentational)
https://www.sketch.com/s/97e144f3-9c62-4ffd-8eca-94451b5536e1/a/25GdJk5

Screenshot 2021-07-13 at 10 53 43
Screenshot 2021-07-13 at 10 53 49

### LINKED ISSUE #173: Populate navigation and sidebar via Contentful GraphQL query

### LINKED ISSUE #174: Link `OnThisPage` component to content sections

### LINKED ISSUE #175: Output page title, markdown content and embedded assets (inline images) for each content page

### LINKED ISSUE #181: Resolve NextJS nested dynamic routes bug
NextJS seems to be throwing a non-sensical error when nesting a dynamic route under a sub-directory (e.g. /components/[slug].tsx). In the mean time, component pages sit at the top level of the URL structure.

### LINKED ISSUE #182: Make Sidebar filter component filter sidebar items

### LINKED ISSUE #184: Create some e2e Cypress tests for legacy pages

### LINKED ISSUE #185: Model, fetch content for and generate legacy generic content pages

### LINKED ISSUE #186: Migrate the legacy `CodeHighlighter` component

### LINKED ISSUE #202: Backfill adapter tests

### PR DESCRIPTION
**Pull request by m7kvqbe1**
## Related issue

Closes #175
Closes #173 
Closes #152
Closes #174
Closes #181
Closes #182
Closes #184
Closes #185 
Closes #186
Closes #202

## Overview

Integrate Contentful data into NextJS application and hydrate presentational components.

## Reason

>The site content and structure needs to be statically generated at build time.

## Work carried out

- [x] Statically generate all Component pages (use slug for lookup)
- [x] Style markdown output for rich text content fields
- [x] Enable embedded asset rendering for rich text content fields
- [x] Populate Sidebar navigation based on Contentful content structure
- [x] Fetch and display RNDS tag dynamically on page load  
- [x] Move timeline to `/timline` route
- [x] Make the `OnThisPage` widget work
- [x] Add some missing SVG icons 
- [x] Enable the Sidebar filter functionality
- [x] Migrate the legacy `CodeHighlighter` component
- [x] Fetch content for and generate generic content pages
- [x] Populate `Masthead` navigation dynamically from Contentful
- [x] Populate `Sidebar` navigation dynamically from Contentful
- [x] Add some automated e2e Cypress tests
- [x] Backfill some missing adapter tests

## Screenshot

Screenshot 2021-08-17 at 12 30 03

## Developer notes

NextJS seems to be throwing a non-sensical error when nesting a dynamic route under a sub-directory (e.g. `/components/[slug].tsx`). In the mean time, component pages sit at the top level of the URL structure. 

Currently working to diagnose the problem.

__This has now been resolved.__

### CODE REVIEW

**Comment by k9dh3zij** [comment]
Thanks @m7kvqbe1 

Some feedback (feel free to ignore anything that's not relevant for right now):

1. Can you increase the h2 top-margin by 20px? This should give the page a bit of white space and help better separate the sections
2. Is it trivial to make 'on this page' to float on the right-hand side?
3. Can we add padding-right to the Filter textbox?
4. Is the [/] button on the filter textbox meant to indicate a shortcut for filtering? Or is it just a clear button? (in which case it should probably be a different icon) It doesn't seem to work with the keyboard even if the button has focus.

**Comment by k9dh3zij** [comment]
A couple more that came out of the content editing demo call today:

5. The storybook link on the left-hand side navigation should not change on different pages it should always link to the Storybook landing page. 

6. On Component content pages there needs to be a link to Storybook which should point to the specific component page on Storybook (is design needed for this?)

**Comment by m7kvqbe1** [comment]
> 2. On Component content pages there needs to be a link to Storybook which should point to the specific component page on Storybook (is design needed for this?)

Please provide design or further clarify where the link needs to be. Just a text link?

**Comment by k9dh3zij** [comment]
> > 1. On Component content pages there needs to be a link to Storybook which should point to the specific component page on Storybook (is design needed for this?)
> 
> Please provide design or further clarify where the link needs to be. Just a text link?

@hxltrhuxze

**Comment by m7kvqbe1** [comment]
Created `CodeHighlighter` component for legacy code blocks:

Screenshot 2021-08-09 at 12 30 06

Screenshot 2021-08-09 at 12 30 53

**Comment by m7kvqbe1** [comment]
@k9dh3zij feedback has been captured and ticketed accordingly, this PR has been superseded by https://github.com/Royal-Navy/docs.royalnavy.io/pull/216

**Pull request closed without merging**
