### PR TITLE
fix(Tsconfig): Add specific Cypress `tsconfig`

### LINKED ISSUE #114: Both Cypress and Jest want to type `expect` - figure out a way to allow both of them authority over the type in the relevant files

### PR DESCRIPTION
**Pull request by thyhjwb6**
## Related issue
Fixes #114 

## Overview
Adds a `tsconfig` for `cypress`.

### CODE REVIEW

**Review by m7kvqbe1 — APPROVED** [review]
👍

**Review by m7kvqbe1 — CHANGES_REQUESTED** [review]
Unfortunately this doesn't seem to be working:

Screenshot 2021-05-25 at 11 55 54

**Comment by m7kvqbe1** [comment]
Nice! This works now!

**Review by m7kvqbe1 — APPROVED** [review]

**Comment by thyhjwb6** [comment]
Closing in favour of #121

**Pull request closed without merging**
